name: phy
dependencies:
  - python=3.5
  - numpy
  - matplotlib
  - scipy
  - h5py
  - cython
  - pyqt=5
  - pandas
  - seaborn
  - pyyaml
  - pytest
  - nose
  - jupyter
  - openpyxl
  - astropy
  - paramiko
  - packaging
  - tqdm
  - pip:
    - klusta
    - klustakwik2
    - vispy
    - requests
    - traitlets
    - six
    - joblib
    - click
    - pycircstat
    - quantities
    - pyrebase
    - xmljson
    - scp
    - send2trash
    - packaging
